import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQ = () => {
  const faqCategories = [
    {
      category: "Getting Started",
      questions: [
        {
          question: "What is RoUI?",
          answer: "RoUI is an AI-powered tool designed specifically for Roblox developers. It allows you to generate professional game UI designs by simply describing what you want or uploading a reference image.",
        },
        {
          question: "How do I start generating UIs?",
          answer: "Simply sign up for a free account, navigate to the generator, and either type a description of the UI you want (e.g., 'medieval inventory with wooden texture') or upload a reference image. Our AI will generate a polished design in seconds.",
        },
        {
          question: "Do I need design experience?",
          answer: "Not at all! RoUI is designed to be accessible to everyone. Just describe what you want in plain English, and our AI handles the rest. No Photoshop or design skills required.",
        },
        {
          question: "What file formats do you support?",
          answer: "Generated UIs are exported as high-resolution PNG files, which can be directly imported into Roblox Studio. We also support JPEG exports for smaller file sizes.",
        },
      ],
    },
    {
      category: "Credits & Billing",
      questions: [
        {
          question: "How do credits work?",
          answer: "Credits are the currency used for generating UIs. Each generation costs 1-5 credits depending on quality settings. Basic quality costs 1 credit, HD costs 3 credits, and Ultra HD with variations costs 5 credits.",
        },
        {
          question: "Do unused credits roll over?",
          answer: "Monthly credits reset at the start of each billing cycle and don't roll over to the next month. We recommend choosing a plan that matches your typical usage.",
        },
        {
          question: "Can I buy additional credits?",
          answer: "Yes! You can purchase additional credit packs at any time from your dashboard. Credit packs never expire and are used after your monthly credits are depleted.",
        },
        {
          question: "What payment methods do you accept?",
          answer: "We accept all major credit cards, debit cards, and PayPal. Enterprise customers can also pay via invoice.",
        },
      ],
    },
    {
      category: "Roblox Integration",
      questions: [
        {
          question: "Are generated UIs compatible with Roblox?",
          answer: "Absolutely! Every UI generated by RoUI is specifically optimized for Roblox. The resolution, aspect ratios, and design choices are all tailored for Roblox Studio.",
        },
        {
          question: "Can I use generated UIs in commercial games?",
          answer: "Yes! All paid plans include a full commercial license. You own complete rights to any UI you generate and can use them in commercial Roblox games.",
        },
        {
          question: "How do I import UIs into Roblox Studio?",
          answer: "Simply download your generated UI as a PNG, then drag and drop it into Roblox Studio's asset manager. From there, you can use it as an ImageLabel or any GUI element.",
        },
        {
          question: "Do you support UI scaling for different screen sizes?",
          answer: "Our designs are created with Roblox's scaling system in mind. We provide guidelines with each export to help you set up proper scaling in your game.",
        },
      ],
    },
    {
      category: "Account & Support",
      questions: [
        {
          question: "How do I upgrade my plan?",
          answer: "Go to your dashboard, click on 'Settings', then 'Subscription'. You can upgrade instantly, and the new credits will be available immediately.",
        },
        {
          question: "Can I cancel my subscription?",
          answer: "Yes, you can cancel anytime from your account settings. You'll continue to have access until the end of your current billing period.",
        },
        {
          question: "How do I get support?",
          answer: "Free users have access to our community Discord. Pro users get priority email support, and Enterprise users receive dedicated support with faster response times.",
        },
        {
          question: "Is there a refund policy?",
          answer: "We offer a 7-day money-back guarantee for first-time subscribers on paid plans. If you're not satisfied, contact support within 7 days of your first payment.",
        },
      ],
    },
  ];

  return (
    <div className="min-h-screen bg-background bg-grid">
      <Navbar />

      {/* Hero */}
      <section className="pt-32 pb-16 bg-gradient-hero">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl sm:text-5xl font-display font-bold text-foreground mb-6">
              Frequently Asked Questions
            </h1>
            <p className="text-lg text-muted-foreground">
              Everything you need to know about RoUI. Can't find your answer? Contact our support team.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ Content */}
      <section className="py-20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto space-y-12">
            {faqCategories.map((category, categoryIndex) => (
              <div key={categoryIndex}>
                <h2 className="text-2xl font-display font-bold text-foreground mb-6">
                  {category.category}
                </h2>
                <Accordion type="single" collapsible className="space-y-4">
                  {category.questions.map((faq, faqIndex) => (
                    <AccordionItem
                      key={faqIndex}
                      value={`${categoryIndex}-${faqIndex}`}
                      className="glass-card rounded-xl px-6 border-none"
                    >
                      <AccordionTrigger className="text-left text-foreground hover:no-underline py-4">
                        {faq.question}
                      </AccordionTrigger>
                      <AccordionContent className="text-muted-foreground pb-4">
                        {faq.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact CTA */}
      <section className="py-16 bg-gradient-hero">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-2xl mx-auto text-center">
            <h2 className="text-2xl font-display font-bold text-foreground mb-4">
              Still have questions?
            </h2>
            <p className="text-muted-foreground mb-6">
              Our support team is here to help. Reach out and we'll get back to you as soon as possible.
            </p>
            <a
              href="mailto:support@roui.app"
              className="inline-flex items-center text-foreground font-medium hover:underline"
            >
              Contact Support →
            </a>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default FAQ;
